services:
  web-server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app #enlaza los archivos de la carpeta al docker, asi no tengo que re build cada vez que se hacen cambios
    ports:
      - '80:80'
    